# Generated by Django 3.1.4 on 2021-01-07 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0004_plan_active'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='plan_type',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='purchase.plan'),
        ),
    ]
