# Generated by Django 3.1.4 on 2021-01-08 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20210107_1117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='plan_type',
            new_name='plan',
        ),
    ]
