# Generated by Django 3.1.4 on 2021-01-14 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20210113_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(default='default-image.png', upload_to='media'),
        ),
    ]
