# Generated by Django 3.1.4 on 2021-01-21 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_auto_20210116_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(default='default-profile-picture.jpg', upload_to=''),
        ),
    ]
