# Generated by Django 3.1.4 on 2020-12-27 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='slug',
            field=models.SlugField(choices=[('Life Time', 'lifetime'), ('Yearly', 'yearly'), ('Monthly', 'monthly')], default='lifetime'),
        ),
    ]
