# Generated by Django 3.1.4 on 2020-12-27 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0002_plan_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='slug',
            field=models.SlugField(choices=[('lifetime', 'Life Time'), ('yearly', 'Yearly'), ('monthly', 'Monthly')], default='lifetime'),
        ),
    ]
