# Generated by Django 3.1.4 on 2021-01-08 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0004_plan_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='active',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
