# Generated by Django 3.1.4 on 2020-12-30 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20201228_1554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='category',
        ),
        migrations.AddField(
            model_name='course',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
