# Generated by Django 3.1.4 on 2021-01-04 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20201230_1102'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ('position',)},
        ),
    ]
