# Generated by Django 3.1.4 on 2021-01-06 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='active',
        ),
    ]
