# Generated by Django 3.1.4 on 2021-01-08 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_remove_course_active'),
        ('courses', '0005_auto_20210104_1211'),
    ]

    operations = [
    ]
