# Generated by Django 3.1.4 on 2021-01-18 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_auto_20210116_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='add_on',
            field=models.DateField(auto_now=True),
        ),
    ]
